# Generated by Django 5.2.11 on 2026-03-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(blank=True, help_text='Suscripción que generó este pago (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='usuarios.suscripcion'),
        ),
    ]
