# Generated by Django 5.2.11 on 2026-03-09 02:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('variedad', models.CharField(help_text='Variedad de uva (ej: Cabernet Sauvignon, Malbec)', max_length=100)),
                ('anio', models.PositiveIntegerField(help_text='Año de cosecha')),
                ('region', models.CharField(help_text='Región de origen (ej: Mendoza, Valle de Colchagua)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vino',
                'verbose_name_plural': 'Vinos',
                'ordering': ['nombre', '-anio'],
            },
        ),
        migrations.CreateModel(
            name='NotaSensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aroma', models.PositiveIntegerField(help_text='Puntuación de aroma (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('color', models.PositiveIntegerField(help_text='Puntuación de color (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sabor', models.PositiveIntegerField(help_text='Puntuación de sabor (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('textura', models.PositiveIntegerField(help_text='Puntuación de textura (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_sensoriales', to='vinos.vino')),
            ],
            options={
                'verbose_name': 'Nota Sensorial',
                'verbose_name_plural': 'Notas Sensoriales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaVinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to=settings.AUTH_USER_MODEL)),
                ('vinos', models.ManyToManyField(blank=True, related_name='bibliotecas', to='vinos.vino')),
            ],
            options={
                'verbose_name': 'Biblioteca de Vinos',
                'verbose_name_plural': 'Bibliotecas de Vinos',
            },
        ),
    ]
